upgrade install script

diff --git a/qinstaller b/qinstaller
--- a/qinstaller
+++ b/qinstaller
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 NAME=qinstaller
-MAIN=http://37.187.144.240:4040
+#MAIN=http://37.187.144.240:4040
 WP_FILE=/root/.$NAME/wp_setup
 WALLET_NAME="qinstaller_setup"
 
@@ -25,9 +25,19 @@ if [ $? -eq 0 ]; then
     while [ -z $PRIVKEY ]; do
         read -p "Enter producer private key: " PRIVKEY
     done
+    while [ -z $MAIN ]; do
+        read -p "Enter url working sp8de network address: " MAIN
+    done
+
+    echo "Checking if network..."
+    cleos -u $MAIN get info > /dev/null 2>&1
+    if [ $? -ne 0 ]; then
+        echo "Invalid network address"
+        exit 1
+    fi
 
     echo "Checking if account with pubkeys exists..."
-    cleos -u $MAIN  get account $PRODNAME | grep $PUBKEY > /dev/null 2>&1
+    cleos -u $MAIN get account $PRODNAME | grep $PUBKEY > /dev/null 2>&1
     if [ $? -ne 0 ]; then
         echo "Account $PRODNAME with pubkey $PUBKEY does not exist, aborting..."
         exit 1
