updating qinstaller; now it creates a helper waller in order to regproducer

diff --git a/qinstaller b/qinstaller
--- a/qinstaller
+++ b/qinstaller
@@ -2,19 +2,22 @@
 
 
 NAME=qinstaller
+WALLET_NAME=qinstaller_setup
 MAIN=http://188.165.193.139:8888
+HOME_DIR=/home/$USER/.$NAME/
+
+
+if [ ! -f "$HOME_DIR/config.ini" ]; then
+    mkdir -p $HOME_DIR
+    cp /etc/$NAME/config.ini $HOME_DIR
+fi
 
 grep -e "\[PRODUCER_NAME\]" \
      -e "\[PRODUCER_PUBLIC_KEY\]" \
      -e "\[PRODUCER_PRIVATE_KEY\]" \
-     -e "\[SERVER_ADDRESS\]" /etc/$NAME/config.ini
+     -e "\[SERVER_ADDRESS\]" $HOME_DIR/config.ini
 
 if [ $? -eq 0 ]; then
-    if [ "$(id -u)" -ne 0 ]
-        then echo "Please run as root to run config setup for qinstaller"
-        exit 1
-    fi
-
     while [ -z $PRODNAME ]; do
         read -p "Enter producer name: " PRODNAME
     done
@@ -29,28 +32,38 @@ if [ $? -eq 0 ]; then
     done
 
     echo "Checking if account with pubkeys exists..."
-    cleos -u $MAIN  get account $PRODNAME | grep $PUBKEY
+    cleos -u $MAIN  get account $PRODNAME | grep $PUBKEY > /dev/null 2>&1
     if [ $? -ne 0 ]; then
         echo "Account $PRODNAME with pubkey $PUBKEY does not exist, aborting..."
         exit 1
     fi
 
     echo "Registering producer node..."
-#    cleos wallet create -n testnet --file /tmp/password_for_testnet_wallet
-#    cleos wallet open -n testnet
-#    cleos wallet unlock -n testnet < /tmp/password_for_testnet_wallet
-#    cleos wallet import -n testnet --private-key $PRIVKEY
+    if [ ! -f $HOME_DIR/wp_setup ]; then
+        cleos wallet create -n $WALLET_NAME --file $HOME_DIR/wp_setup
+        if [ $? -ne 0 ]; then
+            echo "The wallet $WALLET_NAME already exists while key for it in $HOME_DIR/wp_setup is missed"
+            echo "Please, lock and remove wallet $WALLET_NAME manually or restore $HOME_DIR/wp_setup and try again"
+            exit 1
+        fi
+        cleos wallet open -n $WALLET_NAME
+        cleos wallet unlock -n $WALLET_NAME < $HOME_DIR/wp_setup
+        cleos wallet import -n $WALLET_NAME --private-key $PRIVKEY
+    else
+        cleos wallet open -n $WALLET_NAME
+        cleos wallet unlock -n $WALLET_NAME < $HOME_DIR/wp_setup
+    fi
     cleos -u $MAIN system regproducer $PRODNAME $PUBKEY
-#    if [ $? -ne 0 ]; then
-#        echo "Unable to perform registration of validator, aborting..."
-#        exit 1
-#    fi
+    if [ $? -ne 0 ]; then
+        echo "Unable to perform registration of validator, aborting..."
+        exit 1
+    fi
 
-    sed -i "s/\[PRODUCER_NAME\]/$PRODNAME/g" /etc/$NAME/config.ini
-    sed -i "s/\[PRODUCER_PUBLIC_KEY\]/$PUBKEY/g" /etc/$NAME/config.ini
-    sed -i "s/\[PRODUCER_PRIVATE_KEY\]/$PRIVKEY/g" /etc/$NAME/config.ini
-    sed -i "s/\[SERVER_ADDRESS\]/$SERVER/g" /etc/$NAME/config.ini
+    sed -i "s/\[PRODUCER_NAME\]/$PRODNAME/g" $HOME_DIR/config.ini
+    sed -i "s/\[PRODUCER_PUBLIC_KEY\]/$PUBKEY/g" $HOME_DIR/config.ini
+    sed -i "s/\[PRODUCER_PRIVATE_KEY\]/$PRIVKEY/g" $HOME_DIR/config.ini
+    sed -i "s/\[SERVER_ADDRESS\]/$SERVER/g" $HOME_DIR/config.ini
 
 fi
 
-nodeos --config-dir /etc/$NAME/ --delete-all-blocks -e --protocol-features-dir=/tmp/$NAME/protocol_features/ --genesis-json /etc/$NAME/genesis.json --disable-replay-opts
+nodeos --config-dir $HOME_DIR --delete-all-blocks -e --protocol-features-dir=/tmp/$NAME/protocol_features/ --genesis-json /etc/$NAME/genesis.json --disable-replay-opts
